/*
 * This Java source file was generated by the Gradle 'init' task.
 */

 import org.junit.jupiter.api.Test;
 import static org.junit.jupiter.api.Assertions.*;
 
 
 
class mytest {
    @Test void hello() {
        assertEquals("hello", "hello");  
    }
 }
 